version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "ci"
    labels:
      - "type: chore"
      - "area: ci"

  - package-ecosystem: "gitsubmodule"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "build"
    labels:
      - "type: chore"
      - "area: tooling"
